//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace Communications.PCWS_Local_ {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Pocket Campus Web Services - Notices & EventsSoap", Namespace="http://pcws.scar.hull.ac.uk/")]
    public partial class PocketCampusWebServicesNoticesEvents : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListCategorysOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListNoticesOperationCompleted;
        
        private System.Threading.SendOrPostCallback NoticeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListEventsOperationCompleted;
        
        private System.Threading.SendOrPostCallback EventOperationCompleted;
        
        private System.Threading.SendOrPostCallback FeedsOperationCompleted;
        
        private System.Threading.SendOrPostCallback FeedsMediaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PocketCampusWebServicesNoticesEvents() {
            this.Url = global::Communications.Properties.Settings.Default.Communications_Notices_Pocket_x0020_Campus_x0020_Web_x0020_Services_x0020___x0020_Notices_x0020__x0026__x0020_Events;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListCategorysCompletedEventHandler ListCategorysCompleted;
        
        /// <remarks/>
        public event ListNoticesCompletedEventHandler ListNoticesCompleted;
        
        /// <remarks/>
        public event NoticeCompletedEventHandler NoticeCompleted;
        
        /// <remarks/>
        public event ListEventsCompletedEventHandler ListEventsCompleted;
        
        /// <remarks/>
        public event EventCompletedEventHandler EventCompleted;
        
        /// <remarks/>
        public event FeedsCompletedEventHandler FeedsCompleted;
        
        /// <remarks/>
        public event FeedsMediaCompletedEventHandler FeedsMediaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pcws.scar.hull.ac.uk/ListCategorys", RequestNamespace="http://pcws.scar.hull.ac.uk/", ResponseNamespace="http://pcws.scar.hull.ac.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ListCategorys() {
            object[] results = this.Invoke("ListCategorys", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListCategorysAsync() {
            this.ListCategorysAsync(null);
        }
        
        /// <remarks/>
        public void ListCategorysAsync(object userState) {
            if ((this.ListCategorysOperationCompleted == null)) {
                this.ListCategorysOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListCategorysOperationCompleted);
            }
            this.InvokeAsync("ListCategorys", new object[0], this.ListCategorysOperationCompleted, userState);
        }
        
        private void OnListCategorysOperationCompleted(object arg) {
            if ((this.ListCategorysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListCategorysCompleted(this, new ListCategorysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pcws.scar.hull.ac.uk/ListNotices", RequestNamespace="http://pcws.scar.hull.ac.uk/", ResponseNamespace="http://pcws.scar.hull.ac.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ListNotices(int Max, int Category) {
            object[] results = this.Invoke("ListNotices", new object[] {
                        Max,
                        Category});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListNoticesAsync(int Max, int Category) {
            this.ListNoticesAsync(Max, Category, null);
        }
        
        /// <remarks/>
        public void ListNoticesAsync(int Max, int Category, object userState) {
            if ((this.ListNoticesOperationCompleted == null)) {
                this.ListNoticesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListNoticesOperationCompleted);
            }
            this.InvokeAsync("ListNotices", new object[] {
                        Max,
                        Category}, this.ListNoticesOperationCompleted, userState);
        }
        
        private void OnListNoticesOperationCompleted(object arg) {
            if ((this.ListNoticesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListNoticesCompleted(this, new ListNoticesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pcws.scar.hull.ac.uk/Notice", RequestNamespace="http://pcws.scar.hull.ac.uk/", ResponseNamespace="http://pcws.scar.hull.ac.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode Notice(int ID) {
            object[] results = this.Invoke("Notice", new object[] {
                        ID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void NoticeAsync(int ID) {
            this.NoticeAsync(ID, null);
        }
        
        /// <remarks/>
        public void NoticeAsync(int ID, object userState) {
            if ((this.NoticeOperationCompleted == null)) {
                this.NoticeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNoticeOperationCompleted);
            }
            this.InvokeAsync("Notice", new object[] {
                        ID}, this.NoticeOperationCompleted, userState);
        }
        
        private void OnNoticeOperationCompleted(object arg) {
            if ((this.NoticeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NoticeCompleted(this, new NoticeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pcws.scar.hull.ac.uk/ListEvents", RequestNamespace="http://pcws.scar.hull.ac.uk/", ResponseNamespace="http://pcws.scar.hull.ac.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ListEvents(int Max, int Category) {
            object[] results = this.Invoke("ListEvents", new object[] {
                        Max,
                        Category});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListEventsAsync(int Max, int Category) {
            this.ListEventsAsync(Max, Category, null);
        }
        
        /// <remarks/>
        public void ListEventsAsync(int Max, int Category, object userState) {
            if ((this.ListEventsOperationCompleted == null)) {
                this.ListEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListEventsOperationCompleted);
            }
            this.InvokeAsync("ListEvents", new object[] {
                        Max,
                        Category}, this.ListEventsOperationCompleted, userState);
        }
        
        private void OnListEventsOperationCompleted(object arg) {
            if ((this.ListEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListEventsCompleted(this, new ListEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pcws.scar.hull.ac.uk/Event", RequestNamespace="http://pcws.scar.hull.ac.uk/", ResponseNamespace="http://pcws.scar.hull.ac.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode Event(int ID) {
            object[] results = this.Invoke("Event", new object[] {
                        ID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void EventAsync(int ID) {
            this.EventAsync(ID, null);
        }
        
        /// <remarks/>
        public void EventAsync(int ID, object userState) {
            if ((this.EventOperationCompleted == null)) {
                this.EventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEventOperationCompleted);
            }
            this.InvokeAsync("Event", new object[] {
                        ID}, this.EventOperationCompleted, userState);
        }
        
        private void OnEventOperationCompleted(object arg) {
            if ((this.EventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EventCompleted(this, new EventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pcws.scar.hull.ac.uk/Feeds", RequestNamespace="http://pcws.scar.hull.ac.uk/", ResponseNamespace="http://pcws.scar.hull.ac.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Feeds() {
            this.Invoke("Feeds", new object[0]);
        }
        
        /// <remarks/>
        public void FeedsAsync() {
            this.FeedsAsync(null);
        }
        
        /// <remarks/>
        public void FeedsAsync(object userState) {
            if ((this.FeedsOperationCompleted == null)) {
                this.FeedsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFeedsOperationCompleted);
            }
            this.InvokeAsync("Feeds", new object[0], this.FeedsOperationCompleted, userState);
        }
        
        private void OnFeedsOperationCompleted(object arg) {
            if ((this.FeedsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FeedsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pcws.scar.hull.ac.uk/FeedsMedia", RequestNamespace="http://pcws.scar.hull.ac.uk/", ResponseNamespace="http://pcws.scar.hull.ac.uk/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void FeedsMedia() {
            this.Invoke("FeedsMedia", new object[0]);
        }
        
        /// <remarks/>
        public void FeedsMediaAsync() {
            this.FeedsMediaAsync(null);
        }
        
        /// <remarks/>
        public void FeedsMediaAsync(object userState) {
            if ((this.FeedsMediaOperationCompleted == null)) {
                this.FeedsMediaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFeedsMediaOperationCompleted);
            }
            this.InvokeAsync("FeedsMedia", new object[0], this.FeedsMediaOperationCompleted, userState);
        }
        
        private void OnFeedsMediaOperationCompleted(object arg) {
            if ((this.FeedsMediaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FeedsMediaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListCategorysCompletedEventHandler(object sender, ListCategorysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListCategorysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListCategorysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListNoticesCompletedEventHandler(object sender, ListNoticesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListNoticesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListNoticesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void NoticeCompletedEventHandler(object sender, NoticeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NoticeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NoticeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListEventsCompletedEventHandler(object sender, ListEventsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EventCompletedEventHandler(object sender, EventCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FeedsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FeedsMediaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591